<?php
/**
 * Ghora Pay — Main Configuration
 *
 * On Render: set FIREBASE_URL, SITE_URL, API_KEY, CRON_SECRET as
 *            Environment Variables in the Render dashboard.
 *            They override the defaults below automatically.
 *
 * Locally:   Edit the defaults directly, or create a .env file
 *            and load it before this file.
 */

// ── Firebase ──────────────────────────────────────────────────────────────────
// Render env var: FIREBASE_URL
define('FIREBASE_URL', rtrim(
    getenv('FIREBASE_URL') ?: 'https://YOUR-PROJECT-default-rtdb.firebaseio.com',
    '/'
));

// ── Site ──────────────────────────────────────────────────────────────────────
// Render env var: SITE_URL  (e.g. https://ghorapay.onrender.com)
define('SITE_URL',  rtrim(getenv('SITE_URL') ?: 'https://yourdomain.com', '/'));
define('SITE_NAME', 'Ghora Pay');

// ── Android API Key ───────────────────────────────────────────────────────────
// Render env var: API_KEY  (auto-generated by Render, or: openssl rand -hex 32)
define('API_KEY', getenv('API_KEY') ?: 'CHANGE_ME_USE_OPENSSL_RAND_HEX_32');

// ── Cron Secret ───────────────────────────────────────────────────────────────
// Render env var: CRON_SECRET  (auto-generated; paste into cron-job.org header)
// Falls back to API_KEY if not set.
define('CRON_SECRET', getenv('CRON_SECRET') ?: API_KEY);

define('SESSION_NAME', 'gp_sid');

// ── Load Firebase helpers ─────────────────────────────────────────────────────
require_once __DIR__ . '/includes/firebase.php';

// ── Security ──────────────────────────────────────────────────────────────────
function sendSecurityHeaders(): void {
    if (!headers_sent()) {
        header('X-Frame-Options: DENY');
        header('X-Content-Type-Options: nosniff');
        header('X-XSS-Protection: 1; mode=block');
        header('Referrer-Policy: strict-origin-when-cross-origin');
    }
}

function bootSession(): void {
    if (session_status() === PHP_SESSION_ACTIVE) return;
    ini_set('session.cookie_httponly', '1');
    ini_set('session.cookie_samesite', 'Strict');
    ini_set('session.use_strict_mode', '1');
    if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') {
        ini_set('session.cookie_secure', '1');
    }
    // Render sits behind a TLS proxy — detect HTTPS via X-Forwarded-Proto
    if (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https') {
        ini_set('session.cookie_secure', '1');
    }
    session_name(SESSION_NAME);
    session_start();
    if (empty($_SESSION['_init'])) {
        session_regenerate_id(true);
        $_SESSION['_init'] = true;
    }
}
bootSession();
sendSecurityHeaders();

// ── Response helpers ──────────────────────────────────────────────────────────
function jsonResponse(array $data, int $code = 200): void {
    http_response_code($code);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

// ── CSRF ──────────────────────────────────────────────────────────────────────
function csrfToken(): string {
    if (empty($_SESSION['csrf_token'])) {
        $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
    }
    return $_SESSION['csrf_token'];
}
function csrfField(): string {
    return '<input type="hidden" name="csrf_token" value="' . csrfToken() . '">';
}
function verifyCsrf(): void {
    $token = $_POST['csrf_token'] ?? ($_SERVER['HTTP_X_CSRF_TOKEN'] ?? '');
    if (!hash_equals($_SESSION['csrf_token'] ?? '', $token)) {
        http_response_code(403);
        die('CSRF validation failed.');
    }
}

// ── Rate limiting (session-based) ─────────────────────────────────────────────
function checkLoginRate(string $key, int $max = 5, int $window = 300): void {
    $k = 'rate_' . $key;
    if (!isset($_SESSION[$k])) $_SESSION[$k] = ['count' => 0, 'start' => time()];
    if (time() - $_SESSION[$k]['start'] > $window) $_SESSION[$k] = ['count' => 0, 'start' => time()];
    $_SESSION[$k]['count']++;
    if ($_SESSION[$k]['count'] > $max) {
        $wait = $window - (time() - $_SESSION[$k]['start']);
        jsonResponse(['success' => false, 'message' => "Too many attempts. Wait {$wait}s."], 429);
    }
}
function clearLoginRate(string $key): void {
    unset($_SESSION['rate_' . $key]);
}

// ── Misc ──────────────────────────────────────────────────────────────────────
function e(string $s): string {
    return htmlspecialchars($s, ENT_QUOTES | ENT_HTML5, 'UTF-8');
}
function setCorsHeaders(): void {
    header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, X-API-Key');
    if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') exit;
}
function verifyApiKey(): void {
    $key = $_SERVER['HTTP_X_API_KEY'] ?? ($_POST['api_key'] ?? ($_GET['api_key'] ?? ''));
    if (!hash_equals(API_KEY, (string)$key)) {
        jsonResponse(['success' => false, 'message' => 'Unauthorized'], 401);
    }
}
